
# Get current hostname, which does not contain full hostname
- name: Get current hostname
  shell: "hostname"
  register: hostname_value

- set_fact:
    current_hostname: "{{hostname_value.stdout}}"

- set_fact:
    hostname_with_domain: "{{current_hostname}}.{{hostname_domain}}"

- name: "Set hostname with domain"
  hostname:
    name: "{{hostname_with_domain}}"
  when: "hostname_domain not in current_hostname"

- name: "Configure host names in /etc/hosts"
  template:
    src: templates/etc_hosts.j2
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"