- set_fact:
    kafka_download_url: "https://downloads.apache.org/kafka/{{kafka_version}}/kafka_{{kafka_scala_version}}-{{kafka_version}}.tgz"

- set_fact:
    kafka_tgz_local_path: "downloads/kafka_{{kafka_scala_version}}-{{kafka_version}}.tgz"

- set_fact:
    kafka_tgz_vm_path: "/opt/kafka_{{kafka_scala_version}}-{{kafka_version}}.tgz"

- set_fact:
    kafka_vm_dir: "/opt/kafka"

- set_fact:
    kafka_tmp_dir: "/opt/kafka_{{kafka_scala_version}}-{{kafka_version}}"


- name: "Ensure group '{{kafka_linux_group}}' exists"
  group:
    name: "{{kafka_linux_group}}"
    state: present

- name: "Ensure user {{kafka_linux_user}} exists within group: {{kafka_linux_group}}"
  user:
    name: "{{kafka_linux_user}}"
    groups: "{{kafka_linux_group}}"
    append: yes


- name: "Check if Kafka distribution is downloaded"
  local_action: stat path={{kafka_tgz_local_path}}
  become: no
  register: kafka_tgz_local_path_stat

- name: "Download Kafka distribution to local machine, if not yet downloaded"
  local_action: get_url url="{{kafka_download_url}}" dest="{{kafka_tgz_local_path}}"
  become: no
  when: not kafka_tgz_local_path_stat.stat.exists

- name: "Check if Kafka distribution is uploaded to VM"
  stat:
    path: "{{kafka_tgz_vm_path}}"
  become: no
  register: kafka_tgz_vm_path_stat

- name: "Check if Kafka directory exists"
  stat:
    path: "{{kafka_vm_dir}}"
  become: no
  register: kafka_vm_dir_stat

- name: "Copy Kafka distribution to VM host"
  copy:
    src: "{{kafka_tgz_local_path}}"
    dest: "{{kafka_tgz_vm_path}}"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    mode: '0666'
  when: not (kafka_tgz_vm_path_stat.stat.exists or kafka_vm_dir_stat.stat.exists)

- name: "Extract {{kafka_tgz_vm_path}} into {{kafka_vm_dir}}"
  unarchive:
    remote_src: yes
    src: "{{kafka_tgz_vm_path}}"
    dest: "/opt"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
  when: not kafka_vm_dir_stat.stat.exists

- name: "Remove {{kafka_tgz_vm_path}}"
  file:
    path: "{{kafka_tgz_vm_path}}"
    state: absent

- name: "Rename {{kafka_tmp_dir}} {{kafka_vm_dir}}"
  command: "mv {{kafka_tmp_dir}} {{kafka_vm_dir}}"
  when: not kafka_vm_dir_stat.stat.exists


- name: "Configure host names"
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.77.21    kafkanode1.demo.localnet
      192.168.77.22    kafkanode2.demo.localnet
      192.168.77.23    kafkanode3.demo.localnet
      192.168.77.21    kafkanode1
      192.168.77.22    kafkanode2
      192.168.77.23    kafkanode3
      127.0.0.1        localhost


# Fish out broker ID from hostname -- can we avoid this somehow?
- name: Figure out broker ID
  shell: "hostname | tr -dc '0-9' "
  register: kafka_broker_id_result

- set_fact:
    kafka_broker_id: "{{kafka_broker_id_result.stdout}}"


- name: "Set broker ID in Kafka configuration"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^broker.id='
    line: broker.id={{kafka_broker_id}}

- name: Create Zookeeper work directory
  file:
    path: /tmp/zookeeper/
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    state: directory
    mode: '0755'

- name: Write Zookeeper myid file
  template:
    src: templates/zookeeper_myid.j2
    dest: "/tmp/zookeeper/myid"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    mode: "0644"

- name: "Configure Zookeeper tickTime"
  lineinfile:
    path: /opt/kafka/config/zookeeper.properties
    regexp: '^tickTime='
    line: tickTime=2000

- name: "Configure Zookeeper dataDir"
  lineinfile:
    path: /opt/kafka/config/zookeeper.properties
    regexp: '^dataDir='
    line: dataDir=/tmp/zookeeper

- name: "Configure Zookeeper clientPort"
  lineinfile:
    path: /opt/kafka/config/zookeeper.properties
    regexp: '^clientPort='
    line: clientPort=2181

- name: "Configure Zookeeper initLimit"
  lineinfile:
    path: /opt/kafka/config/zookeeper.properties
    regexp: '^initLimit='
    line: initLimit=5

- name: "Configure Zookeeper syncLimit"
  lineinfile:
    path: /opt/kafka/config/zookeeper.properties
    regexp: '^syncLimit='
    line: syncLimit=2

- name: "Configure Zookeeper cluster members"
  blockinfile:
    path: /opt/kafka/config/zookeeper.properties
    block: |
      server.1=192.168.77.21:2888:3888
      server.2=192.168.77.22:2888:3888
      server.3=192.168.77.23:2888:3888

- name: "Setup Zookeeper configuration in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^zookeeper.connect='
    line: zookeeper.connect=192.168.77.21:2181,192.168.77.22:2181,192.168.77.23:2181

- name: "Setup 'offsets.topic.replication.factor' in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^offsets.topic.replication.factor='
    line: offsets.topic.replication.factor=2

- name: "Setup 'transaction.state.log.replication.factor' in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^transaction.state.log.replication.factor='
    line: transaction.state.log.replication.factor=2

- name: "Setup 'transaction.state.log.min.isr' in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^transaction.state.log.min.isr='
    line: transaction.state.log.min.isr=2

- name: Write kafka-zookeeper.service file
  template:
    src: templates/kafka-zookeeper.service.j2
    dest: /etc/systemd/system/kafka-zookeeper.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: Write kafka-zookeeper.service file
  template:
    src: templates/kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: Stop kafka service
  systemd:
    state: stopped
    daemon_reload: yes
    name: kafka

- name: Stop kafka-zookeeper service
  systemd:
    state: stopped
    daemon_reload: yes
    name: kafka-zookeeper


- name: Start kafka-zookeeper service
  systemd:
    state: started
    daemon_reload: yes
    name: kafka-zookeeper

- name: Start kafka service
  systemd:
    state: started
    daemon_reload: yes
    name: kafka

- name: Enable kafka-zookeeper service
  systemd:
    name: kafka-zookeeper
    enabled: yes
    masked: no

- name: Enable kafka service
  systemd:
    name: kafka
    enabled: yes
    masked: no
