

- name: Create Kafka SSL configuration files directory
  file:
    path: "{{ssl_files_directory}}"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    state: directory
    mode: '0700'

- name: "Create Cluster CA files"
  command:
    argv:
      - openssl
      - req
      - -new
      - -newkey
      - rsa:4096
      - -days
      - 3650
      - -x509
      - -subj
      - "/CN=DEMO CA"
      - -keyout
      - root.key
      - -out
      - root.crt
      - -nodes
    creates: root.key
  when: " 'ssl_main_setup_host' in group_names"


- name: "Fetch Root CA key file to command host"
  fetch:
    flat: yes
    src: root.key
    dest: ./ssl/root.key
  when: " 'ssl_main_setup_host' in group_names"

- name: "Fetch Root CA certificate file to command host"
  fetch:
    flat: yes
    src: root.crt
    dest: ./ssl/root.crt
  when: " 'ssl_main_setup_host' in group_names"

- name: "Distribute CA certificate key to cluster nodes"
  copy:
    src: ./ssl/root.key
    dest: root.key
    mode: '0400'
  when: " 'ssl_main_setup_host' not in group_names"

- name: "Distribute CA certificate to cluster nodes"
  copy:
    src: ./ssl/root.crt
    dest: root.crt
    mode: '0400'
  when: " 'ssl_main_setup_host' not in group_names"

- name: Get current hostname
  shell: "hostname"
  register: ssl_hostname_command_result

- set_fact:
    ssl_hostname: "{{ssl_hostname_command_result.stdout}}"


- name: Delete host certificate (if exists)
  ansible.builtin.command:
    argv:
      - keytool
      - -delete
      - -noprompt
      - -alias
      - localhost
      - -keystore
      - "{{ssl_keystore_location}}"
      - -storepass
      - "{{ssl_keystore_password}}"
  ignore_errors: yes


- name: "Generate server key"
  command:
    argv:
      - keytool
      - -noprompt
      - -keystore
      - "{{ssl_keystore_location}}"
      - -validity
      - 365
      - -genkey
      - -storepass
      - "{{ssl_keystore_password}}"
      - -keypass
      - "{{ssl_key_password}}"
      - -dname
      - "CN={{inventory_hostname}}"
      - -ext
      - "SAN=DNS:{{inventory_hostname}}"
      - -storetype
      - pkcs12

- name: "Create Server CSR"
  command:
    argv:
      - keytool
      - -noprompt
      - -keystore
      - "{{ssl_keystore_location}}"
      - -storepass
      - "{{ssl_keystore_password}}"
      - -certreq
      - -file
      - server.csr
    creates: server.csr


- name: "Sign Server certificate"
  command:
    argv:
      - openssl
      - x509
      - -req
      - -in
      - server.csr
      - -days
      - 365
      - -CAcreateserial
      - -CA
      - root.crt
      - -CAkey
      - root.key
      - -out
      - server.crt
      - -passin
      - "pass:{{ssl_key_password}}"
    creates: server.crt



- name: Delete CARoot certificate from truststore (if exists)
  ansible.builtin.command:
    argv:
      - keytool
      - -delete
      - -noprompt
      - -alias
      - CARoot
      - -keystore
      - "{{ssl_truststore_location}}"
      - -storepass
      - "{{ssl_truststore_password}}"
  ignore_errors: yes

- name: Delete CARoot certificate from keystore (if exists)
  ansible.builtin.command:
    argv:
      - keytool
      - -delete
      - -noprompt
      - -alias
      - CARoot
      - -keystore
      - "{{ssl_keystore_location}}"
      - -storepass
      - "{{ssl_keystore_password}}"
  ignore_errors: yes

- name: Delete localhost certificate from keystore (if exists)
  ansible.builtin.command:
    argv:
      - keytool
      - -delete
      - -noprompt
      - -alias
      - localhost
      - -keystore
      - "{{ssl_keystore_location}}"
      - -storepass
      - "{{ssl_keystore_password}}"
  ignore_errors: yes


- name: "Import root.crt to broker truststore"
  ansible.builtin.command:
    argv:
      - keytool
      - -keystore
      - "{{ssl_truststore_location}}"
      - -alias
      - CARoot
      - -import
      - -file
      - root.crt
      - -storepass
      - "{{ssl_truststore_password}}"
      - -keypass
      - "{{ssl_key_password}}"
      - -noprompt

- name: "Import root.crt to broker keystore"
  ansible.builtin.command:
    argv:
      - keytool
      - -keystore
      - "{{ssl_keystore_location}}"
      - -alias
      - CARoot
      - -import
      - -file
      - root.crt
      - -storepass
      - "{{ssl_keystore_password}}"
      - -keypass
      - "{{ssl_key_password}}"
      - -noprompt

- name: "Import server.crt to broker keystore"
  ansible.builtin.command:
    argv:
      - keytool
      - -keystore
      - "{{ssl_keystore_location}}"
      - -alias
      - localhost
      - -import
      - -file
      - server.crt
      - -storepass
      - "{{ssl_keystore_password}}"
      - -keypass
      - "{{ssl_key_password}}"
      - -noprompt

- name: Change trust store ownership and access settings
  ansible.builtin.file:
    path: "{{ssl_truststore_location}}"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    mode: '0600'

- name: Change key store ownership and access settings
  ansible.builtin.file:
    path: "{{ssl_keystore_location}}"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    mode: '0600'


- name: Create Kafka client SSL configuration files directory
  file:
    path: "{{client_ssl_files_directory}}"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    state: directory
    mode: '0755'

- name: Create SSL client truststore
  ansible.builtin.copy:
    remote_src: yes
    src: "{{ssl_truststore_location}}"
    dest: "{{client_ssl_truststore_location}}"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    mode: '0644'

- name: Create SSL client keystore
  ansible.builtin.copy:
    remote_src: yes
    src: "{{ssl_keystore_location}}"
    dest: "{{client_ssl_keystore_location}}"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    mode: '0644'

- name: "Create client SSL configuration"
  template:
    src: templates/client-ssl.properties.j2
    dest: "{{client_ssl_files_directory}}/client-ssl.properties"
    owner: "{{kafka_linux_user}}"
    group: "{{kafka_linux_group}}"
    mode: '0644'

- name: "Set trust store location in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^ssl.truststore.location='
    line: ssl.truststore.location={{ssl_truststore_location}}


- name: "Set trust store password in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^ssl.truststore.password='
    line: ssl.truststore.password={{ssl_truststore_password}}

- name: "Set key store location in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^ssl.keystore.location='
    line: ssl.keystore.location={{ssl_keystore_location}}

- name: "Set key store password in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^ssl.keystore.password='
    line: ssl.keystore.password={{ssl_keystore_password}}

- name: "Set key password in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^ssl.key.password='
    line: ssl.key.password={{ssl_key_password}}

#- name: "Setting inter-broker communication protocol in server.properties"
#  lineinfile:
#    path: /opt/kafka/config/server.properties
#    path: /opt/kafka/config/server.properties
#    regexp: '^security.inter.broker.protocol='
#    line: security.inter.broker.protocol=PLAINTEXT
#
- name: "Configure listeners in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^listeners='
    line: listeners=PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093

- name: "Configure advertised listeners in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^advertised.listeners='
    line: advertised.listeners=PLAINTEXT://{{inventory_hostname}}:9092,SSL://{{inventory_hostname}}:9093

- name: "Configure client authentication setting in server.properties"
  lineinfile:
    path: /opt/kafka/config/server.properties
    regexp: '^ssl.client.auth='
    line: ssl.client.auth=none


- name: Restart kafka service
  systemd:
    state: restarted
    name: kafka

